config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  resources :charges
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'listings#index'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :orders
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validate :correct_iamge_type

  private
  def correct_iamge_type
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
      errors.add(:image, 'Must be a JPEG or PNG')
    elsif image.attached? == false
      errors.add(:image, 'required.')
  end
end
end

app/models/order.rb
class Order < ApplicationRecord


  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchaces, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  # GET /listings
  # GET /listings.json
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to somone else."
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /orders
  # GET /orders.json
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="#">Etsty Demo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "About", pages_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", pages_contact_path, class: 'nav-link' %>
      </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Purchase History", purchases_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sales History", sales_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Manage Listings", seller_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Manage Listings", seller_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: 'nav-link' %>
      </li>
    <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  </div>
</nav>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Etsydemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= tag :meta, :name => "stripe-key", :content => ENV['STRIPE_PUBLIC_KEY'] %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable" id="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
      <%= yield %>

    <p>Copyright 2019</p>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<br>
<div class="form-group row">
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="jumbotron">
      <h1 class="display-3">Hat World</h1>
      <p class="lead">Find hats from all over the world!</p>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p>
</div>
<div class="row">
    <% @listings.each do |listing| %>
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="img-thumbnail">
                <center><%= image_tag(listing.image, width: 200) if listing.image.attached? %>
                  <h5><%= listing.name %></h5>
                  <h6><%= listing.price %></h6>
                  <p><%= link_to 'Buy', listing, class: 'btn btn-info' %></p>
                  <p><%= "Sold by #{listing.user.name}" %></p>
                  <% if (user_signed_in?) && (current_user == listing.user) %>
                  <p><%= link_to 'Edit', edit_listing_path(listing) %> | <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></p></center>
                  <% end %>
              </div>
            </div>
    <% end %>
    </div>
    <% if(user_signed_in?) %>
    <%= link_to 'New Listing', new_listing_path %>
    <% end %>
<br>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Image</th>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Price</th>
    <th scope="col">Action</th>
  </tr>
</thead>
<tbody>
<% @listings.each do |listing| %>
<tr>
  <td scope="row"><%= image_tag(listing.image, width: 200) if listing.image.attached? %></td>
  <td><%= listing.name %></td>
  <td><%= number_to_currency(listing.price) %></td>
  <td><%= listing.description %></td>
  <td>
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <button type="button" class="btn btn-primary"><a class="dropdown-item" href="#"><%= link_to "View", listing %></a></button>
  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 40px, 0px); top: 0px; left: 0px; will-change: transform;">
      <% if user_signed_in? %>
      <a class="dropdown-item" href="#"><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link"  %></a>
      <a class="dropdown-item" href="#">  <%= link_to "Destroy", listing, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-link"%></a>
      <% end %>
    </div>
  </div>
</div>
  </td>
</tr>
<% end %>
</tbody>
</table>

<br>

app/views/listings/show.html.erb
<p>
  <%= image_tag(@listing.image, width: 300) if @listing.image.attached? %>
</p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %><br><br>
  <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary", data: {no_turbolink: true} %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>
<% if (current_user == @listing.user) %>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<% end %>
<%= link_to 'Back', listings_path %>

app/views/orders/_form.html.erb
<%= form_with(model: [@listing, @order], id: "new_order", class: "new_order") do |form| %> 
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number"} %>
  </div>

  <div class="field">
    <%= label_tag :card_code, "CVC" %>
    <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc"} %>
  </div>

  <div class="field">
    <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month"} %>
    <%=  select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10 }, {:name => nil, :'data-stripe' => "exp-year"} %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your sales history</h2>
</div>
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Image</th>
    <th scope="col">Item</th>
    <th scope="col">Price</th>
    <th scope="col">Seller</th>
    <th scope="col">Date Purchased</th>
  </tr>
</thead>
<tbody>
<% @orders.each do |order| %>
<tr>
  <td scope="row"><%= image_tag(order.listing.image, width: 200) if order.listing.image.attached? %></td>
  <td><%= order.listing.name %></td>
  <td><%= number_to_currency(order.listing.price) %></td>
  <td><%= order.seller.name %></td>
  <td><% order.created_at.strftime("%B %-d, %Y") %></td>
  <td>
  </td>
</tr>
<% end %>
</tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Your sales history</h2>
</div>
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">Image</th>
    <th scope="col">Item</th>
    <th scope="col">Price</th>
    <th scope="col">Customer</th>
    <th scope="col">Date Sold</th>
  </tr>
</thead>
<tbody>
<% @orders.each do |order| %>
<tr>
  <td scope="row"><%= image_tag(order.listing.image, width: 200) if order.listing.image.attached? %></td>
  <td><%= order.listing.name %></td>
  <td><%= number_to_currency(order.listing.price) %></td>
  <td><%= order.buyer.name %></td>
  <td><% order.created_at.strftime("%B %-d, %Y") %></td>
  <td>
  </td>
</tr>
<% end %>
</tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>Esty Demo is an online shopping platform to sell and buy products from other users.</p>

app/views/pages/contact.html.erb
<h1>Email me @ sepulveda.israel@gmail.com</h1>
<p>Call me at (910) 364 - 1404 </p>